package com.mycompany.nexuseguros;

import clases.Usuario;
import clases.clienteDatos;
import com.login.login;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;


public class dashboardCliente extends javax.swing.JFrame {
    private clienteDatos cliente;
  
    public dashboardCliente(Usuario usuario) {
        this.cliente = cliente; 
        initComponents();
        initStyles();
        setDate();
        initContent();
        mostrarDatosUsuario();
        
    }
    private void mostrarDatosUsuario() {
        if (cliente != null) {
            jLabel1.setText("Bienvenido " + cliente.getNombre());
           
        }
    }

    private void initStyles(){
        /*nombreSistema.putClientProperty( "FlatLaf.style", "font: 20 $light.font" );
        nombreSistema.setForeground(Color.black);*/
    }
    private void setDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        dateText.setText(dia + " de " + meses[month - 1] + " de " + year);
    }
    
    private void initContent(){
        ShowJPanel(new inicioC());
        
    }
    private void ShowJPanel(JPanel c){
        c.setSize(730, 508);
        c.setLocation(0,0);
        
        contentCliente.removeAll();
        contentCliente.add(c, BorderLayout.CENTER);
        contentCliente.revalidate();
        contentCliente.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonInicioC = new javax.swing.JButton();
        botonPerfilC = new javax.swing.JButton();
        botonSesionC = new javax.swing.JButton();
        botonSegurosC = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        contentCliente = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(34, 34, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        botonInicioC.setBackground(new java.awt.Color(34, 34, 34));
        botonInicioC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonInicioC.setForeground(new java.awt.Color(255, 255, 255));
        botonInicioC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio.png"))); // NOI18N
        botonInicioC.setText("Inicio");
        botonInicioC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonInicioC.setBorderPainted(false);
        botonInicioC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicioC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonInicioC.setIconTextGap(10);
        botonInicioC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioCMouseExited(evt);
            }
        });
        botonInicioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioCActionPerformed(evt);
            }
        });

        botonPerfilC.setBackground(new java.awt.Color(34, 34, 34));
        botonPerfilC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPerfilC.setForeground(new java.awt.Color(255, 255, 255));
        botonPerfilC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        botonPerfilC.setText("Perfil");
        botonPerfilC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonPerfilC.setBorderPainted(false);
        botonPerfilC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPerfilC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPerfilC.setIconTextGap(10);
        botonPerfilC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPerfilCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPerfilCMouseExited(evt);
            }
        });
        botonPerfilC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerfilCActionPerformed(evt);
            }
        });

        botonSesionC.setBackground(new java.awt.Color(34, 34, 34));
        botonSesionC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonSesionC.setForeground(new java.awt.Color(255, 255, 255));
        botonSesionC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        botonSesionC.setText("Cerrar Sesion");
        botonSesionC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonSesionC.setBorderPainted(false);
        botonSesionC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSesionC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSesionC.setIconTextGap(10);
        botonSesionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSesionCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSesionCMouseExited(evt);
            }
        });
        botonSesionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesionCActionPerformed(evt);
            }
        });

        botonSegurosC.setBackground(new java.awt.Color(34, 34, 34));
        botonSegurosC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonSegurosC.setForeground(new java.awt.Color(255, 255, 255));
        botonSegurosC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seguro.png"))); // NOI18N
        botonSegurosC.setText("Seguros Contratados");
        botonSegurosC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonSegurosC.setBorderPainted(false);
        botonSegurosC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSegurosC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSegurosC.setIconTextGap(10);
        botonSegurosC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSegurosCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSegurosCMouseExited(evt);
            }
        });
        botonSegurosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSegurosCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonInicioC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonSesionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonPerfilC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(botonSegurosC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botonInicioC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonPerfilC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSegurosC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(botonSesionC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        header.setBackground(new java.awt.Color(97, 192, 191));
        header.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");

        dateText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("{dayname} {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(dateText)
                .addGap(55, 55, 55))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateText))
        );

        javax.swing.GroupLayout contentClienteLayout = new javax.swing.GroupLayout(contentCliente);
        contentCliente.setLayout(contentClienteLayout);
        contentClienteLayout.setHorizontalGroup(
            contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentClienteLayout.setVerticalGroup(
            contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioCMouseEntered
        botonInicioC.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_botonInicioCMouseEntered

    private void botonInicioCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioCMouseExited
        botonInicioC.setBackground(new Color(34,34,34));
    }//GEN-LAST:event_botonInicioCMouseExited

    private void botonInicioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioCActionPerformed
        ShowJPanel(new inicioC());
    }//GEN-LAST:event_botonInicioCActionPerformed

    private void botonPerfilCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPerfilCMouseEntered
        botonPerfilC.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_botonPerfilCMouseEntered

    private void botonPerfilCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPerfilCMouseExited
        botonPerfilC.setBackground(new Color(34,34,34));
    }//GEN-LAST:event_botonPerfilCMouseExited

    private void botonPerfilCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerfilCActionPerformed
        ShowJPanel(new perfilC(cliente));
    }//GEN-LAST:event_botonPerfilCActionPerformed

    private void botonSesionCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSesionCMouseEntered
        botonSesionC.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_botonSesionCMouseEntered

    private void botonSesionCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSesionCMouseExited
        botonSesionC.setBackground(new Color(34,34,34));
    }//GEN-LAST:event_botonSesionCMouseExited

    private void botonSesionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSesionCActionPerformed
        login b1 = new login();
        b1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSesionCActionPerformed

    private void botonSegurosCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSegurosCMouseEntered
        botonSegurosC.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_botonSegurosCMouseEntered

    private void botonSegurosCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSegurosCMouseExited
        botonSegurosC.setBackground(new Color(34,34,34));
    }//GEN-LAST:event_botonSegurosCMouseExited

    private void botonSegurosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSegurosCActionPerformed
        ShowJPanel(new contratacionesC());
    }//GEN-LAST:event_botonSegurosCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuarioLogueado = null;
                dashboardCliente cliente = new dashboardCliente(usuarioLogueado);
                cliente.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicioC;
    private javax.swing.JButton botonPerfilC;
    private javax.swing.JButton botonSegurosC;
    private javax.swing.JButton botonSesionC;
    private javax.swing.JPanel contentCliente;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
